/**
 * Norm parameters for dog MBTI z-score calibration.
 *
 * Computed from Dataset_CBARQ.xlsx (Italian C-BARQ validation).
 *
 * Generated by: scripts/compute-dog-norms.py
 */

import type { CbarqFactor } from './types';

export const DOG_NORM_PARAMS: Record<CbarqFactor, { mean: number; stdDev: number }> = {
  F1: { mean: 0.994679, stdDev: 1.60614 },
  F10: { mean: 0.702441, stdDev: 0.579472 },
  F11: { mean: 2.196073, stdDev: 1.085863 },
  F12: { mean: 0.197072, stdDev: 0.583546 },
  F13: { mean: 0.955439, stdDev: 1.068499 },
  F2: { mean: 1.319301, stdDev: 1.525806 },
  F3: { mean: 0.35762, stdDev: 0.780062 },
  F4: { mean: 1.649675, stdDev: 1.701407 },
  F5: { mean: 3.534399, stdDev: 2.39786 },
  F6: { mean: 1.783078, stdDev: 1.258015 },
  F7: { mean: 3.482429, stdDev: 1.175734 },
  F8: { mean: 1.862155, stdDev: 0.681317 },
  N_TYPE: { mean: 0.450063, stdDev: 0.890871 },
};
